#!/usr/bin/env node
// Compose skills/adhd-unslop/SKILL.md from overlay/*.md and the pristine
// upstream bodies, slice it into three hook chunks, write the chunk manifest,
// stamp VERSION into the manifests, and copy upstream licenses into the skill.
//
//   node tools/build.mjs           write everything
//   node tools/build.mjs --check   exit 1 if any generated file is stale

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { sha256, stripFrontmatter, TOTAL_CHUNKS } from "../hooks/lib.mjs";

export const repo = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
export const SKILL_DIR = path.join(repo, "skills", "adhd-unslop");
export const SKILL_PATH = path.join(SKILL_DIR, "SKILL.md");
export const CHUNK_DIR = path.join(repo, "hooks", "chunks");

const read = (...p) => fs.readFileSync(path.join(repo, ...p), "utf8");

export function loadPins() {
  return JSON.parse(read("tools", "upstream.json")).upstreams;
}

export function markers(name, pins) {
  const pin = pins[name];
  return {
    begin: `<!-- BEGIN upstream ${name} ${pin.repo}/${pin.files["SKILL.md"].path} @${pin.commit} -->\n`,
    end: `<!-- END upstream ${name} -->\n`,
  };
}

export function frontmatter() {
  return [
    "---",
    "name: adhd-unslop",
    "description: 'Cut AI tells from all writing and shape direct replies for a reader with ADHD. Embeds the i-have-adhd and unslop skills unchanged and adds one tie-breaker: on a conflict, i-have-adhd wins in a direct reply and unslop wins everywhere else. Invoke with /adhd-unslop; stays on until \"normal mode\".'",
    "disable-model-invocation: true",
    "license: MIT",
    "metadata:",
    '  tags: "ADHD, Writing, Output Style, Formatting"',
    '  category: "productivity"',
    "---",
    "",
  ].join("\n");
}

function endsWithNewline(s) {
  return s.endsWith("\n") ? s : s + "\n";
}

export function compose() {
  const pins = loadPins();
  const overlay = (f) => endsWithNewline(read("overlay", f));
  const upstreamBody = (name) => endsWithNewline(stripFrontmatter(read("upstream", name, "SKILL.md")));
  const adhd = markers("i-have-adhd", pins);
  const unslop = markers("unslop", pins);

  const generatedNote = "<!-- GENERATED by tools/build.mjs. Edit overlay/*.md or bump a pin in tools/upstream.json, then rebuild. -->\n";
  const chunk1 = generatedNote + overlay("00-intro.md") + "\n" + overlay("10-precedence.md") + "\n" + overlay("20-lifecycle.md") + "\n";
  const chunk2 = adhd.begin + upstreamBody("i-have-adhd") + adhd.end + "\n";
  const chunk3 = unslop.begin + upstreamBody("unslop") + unslop.end + "\n" + overlay("90-final-check.md");
  const chunks = [chunk1, chunk2, chunk3];
  const body = chunks.join("");
  const manifest = {
    generatedBy: "tools/build.mjs",
    compositeSha256: sha256(body),
    chunks: chunks.map((c, i) => ({
      index: i + 1,
      file: `${i + 1}.md`,
      sha256: sha256(c),
      bytes: Buffer.byteLength(c, "utf8"),
      utf16Units: c.length,
    })),
  };
  return { frontmatter: frontmatter(), body, skill: frontmatter() + body, chunks, manifest, pins };
}

export function stampVersion(version) {
  const files = [
    [".claude-plugin/plugin.json", (j) => { j.version = version; }],
    [".codex-plugin/plugin.json", (j) => { j.version = version; }],
    [".claude-plugin/marketplace.json", (j) => { for (const p of j.plugins) p.version = version; }],
  ];
  const out = [];
  for (const [rel, mutate] of files) {
    const j = JSON.parse(read(rel));
    mutate(j);
    out.push([rel, JSON.stringify(j, null, 2) + "\n"]);
  }
  return out;
}

export function noticeText(pins) {
  const lines = [
    "# Notice",
    "",
    "This skill embeds two upstream works, byte-for-byte after removing their",
    "YAML frontmatter. Each keeps its own MIT license in this directory.",
    "",
    "| Upstream | Repository | Commit | File | License file |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const [name, pin] of Object.entries(pins)) {
    lines.push(`| ${name} | https://github.com/${pin.repo} | ${pin.commit} | ${pin.files["SKILL.md"].path} | ${name}.LICENSE |`);
  }
  lines.push("", "The unslop skill in pstack-claude is a port of Lauren Tan's pstack for Cursor.", "");
  return lines.join("\n");
}

export function expectedFiles() {
  const c = compose();
  const version = read("VERSION").trim();
  const files = new Map();
  files.set(path.relative(repo, SKILL_PATH), c.skill);
  c.chunks.forEach((chunk, i) => files.set(`hooks/chunks/${i + 1}.md`, chunk));
  files.set("hooks/chunks/manifest.json", JSON.stringify(c.manifest, null, 2) + "\n");
  for (const [rel, text] of stampVersion(version)) files.set(rel, text);
  for (const name of Object.keys(c.pins)) {
    files.set(`skills/adhd-unslop/LICENSES/${name}.LICENSE`, read("upstream", name, "LICENSE"));
  }
  files.set("skills/adhd-unslop/LICENSES/NOTICE.md", noticeText(c.pins));
  return files;
}

export function staleFiles() {
  const stale = [];
  for (const [rel, text] of expectedFiles()) {
    let current = null;
    try { current = read(rel); } catch { /* missing */ }
    if (current !== text) stale.push(rel);
  }
  return stale;
}

export function writeAll() {
  for (const [rel, text] of expectedFiles()) {
    const abs = path.join(repo, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, text);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const stale = staleFiles();
    if (stale.length) {
      console.error("stale generated files:\n  " + stale.join("\n  "));
      process.exit(1);
    }
    console.log("generated files are current");
  } else {
    writeAll();
    const c = compose();
    console.log(`wrote ${path.relative(repo, SKILL_PATH)} (${c.skill.length} chars, body sha256 ${c.manifest.compositeSha256.slice(0, 12)})`);
    c.manifest.chunks.forEach((m) => console.log(`  chunk ${m.index}: ${m.utf16Units} chars payload`));
    if (c.chunks.length !== TOTAL_CHUNKS) throw new Error("chunk count drifted from lib.TOTAL_CHUNKS");
  }
}
